### PR TITLE
APPS-654 Incorporate useSetAppHeight() hook

### PR DESCRIPTION
**Pull request by tamarazuk**
This PR incorporates the useSetAppHeight() hook that was recently introduced in the UI Kit. It also introduces a new CSS file as setting the body margin to 0 was required for this hook to work as intended.

### CODE REVIEW

**Comment by deivamagalhaes** [comment]
> It also introduces a new CSS file as setting the body margin to 0 was required for this hook to work as intended.

How we are going to handle this issue if a developer is not using the app-template? Are we going to add this requirement to the documentation?

**Review by deivamagalhaes — APPROVED** [review]
The code looks pretty straightforward, I just have a question about the CSS requirement.

**Comment by tamarazuk** [comment]
> How we are going to handle this issue if a developer is not using the app-template? Are we going to add this requirement to the documentation?

That's a good callout and I've been mulling on it. There are a few ways to approach this but I think the best would be to find a way to address it in UI Kit so it's hands-off and doesn't require documentation updates

**Comment by tamarazuk** [comment]
@deivamagalhaes added a card so it doesn't get lost: https://helpscout.atlassian.net/browse/APPS-669

thanks for the reminder!

**Pull request merged**
